= rina.apps.manager

RINA experimental CDAP connect java bindings tester.
It translates native GPB CDAP requests to a JSON CDAP requests and responses, suitable for internal use within the CDAP manager.

== Install instructions

. Install Java (if not available)

. Install google-protobuf

. Install google-protobuf java runtime

. Install maven (required by the IRATI stack)


== Building instructions

. Build the RINA stack with Java bindings enabled. Complete instructions can be found on the link:http://github.com/IRATI[IRATI repository].

. Run in the project root:

[source]
----
./gradlew build
----

This will download the correct version of gradle, and install dependencies.


== Packaging instructions.

To package the application for installation on another RINA computer.

1. Run: 

[source]
----
./gradlew distTar

----

2. And then copy build/distributions/tmanager.tar to the required machine, and untar.

3. Setup LD_LIBRARY_PATH correctly to include librina.

4. Run the ./bin/tmanager script.
